name: weatherapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+2

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2 # The HTTP package is used to make network requests.   
  provider: ^6.1.5  # The Provider package is used for state management in Flutter applications.
  intl: ^0.19.0
  get: ^4.6.5 # for state management and context less stuff
  logger: ^2.0.2 # log events in clear way insted of (print)
  flutter_screenutil: ^5.9.0 # make app responsive
  dio: ^5.4.0 # for api requests
  http_mock_adapter: ^0.6.1 # mocking dio for testing
  pretty_dio_logger: ^1.0.0 # for dio api logging and debugging
  shared_preferences: ^2.2.2 # shared preferences persistence key value store
  location: ^5.0.3 # for location
  flutter_launcher_icons: ^0.13.1 # change app icon
  flutter_svg: ^2.0.9 # for svg icons
  smooth_page_indicator: ^1.1.0 # for onboarding screen
  flutter_spinkit: ^5.2.0 # for loading indicator
  cached_network_image: ^3.3.1 # for network image
  carousel_slider: ^5.1.1 # for image slider
  shimmer: ^3.0.0 # for shimmer effect
  step_progress_indicator: ^1.0.2 # for progress indicator
  lottie: ^3.0.0 # for Adobe After Effects animations
  flutter_animate: ^4.2.0+1 # for animation

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#6151C3"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/data/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
